name: Deploy

on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY: {}  
      EC2_PUBLIC_IP: {}    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Node.js dependencies
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} "source ~/.nvm/nvm.sh && cd F-BEE24001186-km7-jua-Basic-Banking-System-ch4 && git pull origin main && npm install && npx prisma generate && pm2 restart my-app --update-env && pm2 save"
